name: pacops
on:
  schedule:
    - cron: '0 5 * * *'
jobs:
  check-ms-edge-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: PacOps in Docker
        uses: docker://ejiek/pacops:next
        with:
          entrypoint: /usr/bin/pacops
          args: package general/microsoft-edge-dev-bin/PKGBUILD
        env:
          PACOPS_COMMIT: true
          PACOPS_PUSH: true
          PACOPS_SRCINFO: true
          GIT_AUTHOR_NAME: ${{ github.actor }}
          GIT_AUTHOR_EMAIL: ejiek@mail.ru
          GIT_COMMITTER_NAME: ${{ github.actor }}
          GIT_COMMITTER_EMAIL: ejiek@mail.ru
